### ISSUE TITLE
Create standalone spec text

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-regexp-lookbehind#1]
We have a spec diff against a year-old copy of the spec at https://github.com/claudepache/ecma262/commit/b37e618f858fe75d241dd677e8258d908b3bc182 . However, for ease of review, this should be reformatted as a standalone ecmarkup document which can be rendered.

**Comment by IgnoredAmbience** [comment]
Although briefly discussed in person at the meeting, I thought a concrete follow-up would be helpful. Would you like any help with (initially) the editorial work for this proposal?

**Comment by littledan** [comment]
@edgemaster Sure, that would be great if you want to take an initial stab at this. I'd like to propose this for Stage 3 at the next meeting, so that means that we should get some good spec text by the end of the month. You can get ecmarkup [here](https://github.com/bterlson/ecmarkup), and see an example of standalone proposal text [here](https://github.com/tc39/proposal-private-fields). Note the use of ins and del tags when modifying existing parts of the spec.
